receivers:
  otlp:
    protocols:
      grpc:
  ema:
    interval: 10s 

processors:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp,ema]
      processors: []
      exporters: [logging]  
