receivers:
  otlp:
    protocols:
      grpc:
  ema:
    collection_interval: 5s 
    endpoint: localhost:43034
    metrics:
      vectorh.cpuload:
        enabled: true 
      # vectorh.connectedSessions.connect_count:
      #   enabled: true
      # vectorh.connectedSessions.connect_limit:
      #   enabled: true


processors:

exporters:
  logging:
    loglevel: debug 
  otlp:
    endpoint: 0.0.0.0:4320
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp,ema]
      processors: []
      exporters: [logging,otlp]  
