receivers:
  otlp:
    protocols:
      grpc:
  ema:
    collection_interval: 5s 
    metrics:
      vectorh.cpuload:
        enabled: false 
      # vectorh.connectedSessions.connect_count:
      #   enabled: true
      # vectorh.connectedSessions.connect_limit:
      #   enabled: true


processors:

exporters:
  logging:
    loglevel: debug 

service:
  pipelines:
    metrics:
      receivers: [otlp,ema]
      processors: []
      exporters: [logging]  
